export const mockData = {
  data: [
    {
      name: "Mixmax",
      budget_name: "Software subscription",
      owner_id: "Rajesh",
      spent: {
        value: 0,
        currency: "SGD",
      },
      available_to_spend: { value: 100, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "QuickBooks",
      budget_name: "Software subscription",
      owner_id: "Rajat",
      spent: {
        value: 10,
        currency: "SGD",
      },
      available_to_spend: { value: 90, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Motion",
      budget_name: "Software subscription",
      owner_id: "Vishal",
      spent: {
        value: 50,
        currency: "USD",
      },
      available_to_spend: { value: 50, currency: "USD" },
      card_type: "subscription",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Pandadoc",
      budget_name: "Software subscription",
      owner_id: "Mayank",
      spent: {
        value: 90,
        currency: "SGD",
      },
      available_to_spend: { value: 10, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Mixmax",
      budget_name: "Software subscription",
      owner_id: "Rajesh",
      spent: {
        value: 0,
        currency: "SGD",
      },
      available_to_spend: { value: 100, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "QuickBooks",
      budget_name: "Software subscription",
      owner_id: "Rajat",
      spent: {
        value: 10,
        currency: "SGD",
      },
      available_to_spend: { value: 90, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Motion",
      budget_name: "Software subscription",
      owner_id: "Vishal",
      spent: {
        value: 50,
        currency: "USD",
      },
      available_to_spend: { value: 50, currency: "USD" },
      card_type: "subscription",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Pandadoc",
      budget_name: "Software subscription",
      owner_id: "Mayank",
      spent: {
        value: 90,
        currency: "SGD",
      },
      available_to_spend: { value: 10, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Mixmax",
      budget_name: "Software subscription",
      owner_id: "Rajesh",
      spent: {
        value: 0,
        currency: "SGD",
      },
      available_to_spend: { value: 100, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "QuickBooks",
      budget_name: "Software subscription",
      owner_id: "Rajat",
      spent: {
        value: 10,
        currency: "SGD",
      },
      available_to_spend: { value: 90, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Motion",
      budget_name: "Software subscription",
      owner_id: "Vishal",
      spent: {
        value: 50,
        currency: "USD",
      },
      available_to_spend: { value: 50, currency: "USD" },
      card_type: "subscription",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Pandadoc",
      budget_name: "Software subscription",
      owner_id: "Mayank",
      spent: {
        value: 90,
        currency: "SGD",
      },
      available_to_spend: { value: 10, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Mixmax",
      budget_name: "Software subscription",
      owner_id: "Rajesh",
      spent: {
        value: 0,
        currency: "SGD",
      },
      available_to_spend: { value: 100, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "QuickBooks",
      budget_name: "Software subscription",
      owner_id: "Rajat",
      spent: {
        value: 10,
        currency: "SGD",
      },
      available_to_spend: { value: 90, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Motion",
      budget_name: "Software subscription",
      owner_id: "Vishal",
      spent: {
        value: 50,
        currency: "USD",
      },
      available_to_spend: { value: 50, currency: "USD" },
      card_type: "subscription",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Pandadoc",
      budget_name: "Software subscription",
      owner_id: "Mayank",
      spent: {
        value: 90,
        currency: "SGD",
      },
      available_to_spend: { value: 10, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Mixmax",
      budget_name: "Software subscription",
      owner_id: "Rajesh",
      spent: {
        value: 0,
        currency: "SGD",
      },
      available_to_spend: { value: 100, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "QuickBooks",
      budget_name: "Software subscription",
      owner_id: "Rajat",
      spent: {
        value: 10,
        currency: "SGD",
      },
      available_to_spend: { value: 90, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Motion",
      budget_name: "Software subscription",
      owner_id: "Vishal",
      spent: {
        value: 50,
        currency: "USD",
      },
      available_to_spend: { value: 50, currency: "USD" },
      card_type: "subscription",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Pandadoc",
      budget_name: "Software subscription",
      owner_id: "Mayank",
      spent: {
        value: 90,
        currency: "SGD",
      },
      available_to_spend: { value: 10, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Mixmax",
      budget_name: "Software subscription",
      owner_id: "Rajesh",
      spent: {
        value: 0,
        currency: "SGD",
      },
      available_to_spend: { value: 100, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "QuickBooks",
      budget_name: "Software subscription",
      owner_id: "Rajat",
      spent: {
        value: 10,
        currency: "SGD",
      },
      available_to_spend: { value: 90, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Motion",
      budget_name: "Software subscription",
      owner_id: "Vishal",
      spent: {
        value: 50,
        currency: "USD",
      },
      available_to_spend: { value: 50, currency: "USD" },
      card_type: "subscription",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Pandadoc",
      budget_name: "Software subscription",
      owner_id: "Mayank",
      spent: {
        value: 90,
        currency: "SGD",
      },
      available_to_spend: { value: 10, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Mixmax",
      budget_name: "Software subscription",
      owner_id: "Rajesh",
      spent: {
        value: 0,
        currency: "SGD",
      },
      available_to_spend: { value: 100, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "QuickBooks",
      budget_name: "Software subscription",
      owner_id: "Rajat",
      spent: {
        value: 10,
        currency: "SGD",
      },
      available_to_spend: { value: 90, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Motion",
      budget_name: "Software subscription",
      owner_id: "Vishal",
      spent: {
        value: 50,
        currency: "USD",
      },
      available_to_spend: { value: 50, currency: "USD" },
      card_type: "subscription",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Pandadoc",
      budget_name: "Software subscription",
      owner_id: "Mayank",
      spent: {
        value: 90,
        currency: "SGD",
      },
      available_to_spend: { value: 10, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Mixmax",
      budget_name: "Software subscription",
      owner_id: "Rajesh",
      spent: {
        value: 0,
        currency: "SGD",
      },
      available_to_spend: { value: 100, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "QuickBooks",
      budget_name: "Software subscription",
      owner_id: "Rajat",
      spent: {
        value: 10,
        currency: "SGD",
      },
      available_to_spend: { value: 90, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Motion",
      budget_name: "Software subscription",
      owner_id: "Vishal",
      spent: {
        value: 50,
        currency: "USD",
      },
      available_to_spend: { value: 50, currency: "USD" },
      card_type: "subscription",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
    {
      name: "Pandadoc",
      budget_name: "Software subscription",
      owner_id: "Mayank",
      spent: {
        value: 90,
        currency: "SGD",
      },
      available_to_spend: { value: 10, currency: "SGD" },
      card_type: "burner",
      expiry: "9 feb",
      limit: 100,
      status: "active",
    },
  ],
};
